version: 2

macros:
  - name: rolling_average_n_periods
    description: A macro to calculate the rolling average of a time period. The default time period is 7 days.
    arguments:
      - name: column_name
        type: string
        description: The name of the column you want to convert
      - name: partition_by
        type: string
        description: The value you want to partition by
      - name: order_by
        type: timestamp
        description: the date value you want to order by. Default is created_at
      - name: time_period
        type: int
        description: the time period you want to calculate the rolling average over. The default value is 6 to calculate over a 7 day period.
      - name: time_range
        type: string
        description: the time range (day, week, month) for your rolling calc based on your other date columns
